import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { cn } from "@/lib/utils";
import LandingLayout from "./(landing)/layout";
import Navbar from "./(landing)/_components/Navbar";




const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={cn(inter.className, "h-full")}
        
      >
      <LandingLayout >

        <Navbar />
        {children}
        
      </LandingLayout>
        
      </body>
    </html>
  );
}

